version: 2.1
description: Adds a new dns record on DNSimple

commands:
  create_dns_record:
    description: Create a dnsnimple record for the project
    parameters:
      token:
        description: api token, can be retrieved from dnsnimple's automation page, or here https://support.dnsimple.com/articles/api-access-token/
        type: string
        default: ""
      account_id:
        description: DNSimple's account id
        type: string
        default: ""
      zone_id:
        description: Zone id or the domain you want to manage
        type: string
        default: ""
      subdomain:
        description: name of the new record. For more information, please see dnsimple documentation
        type: string
        default: ""
      content:
        description: content of the new record, to which to point to
        type: string
        default: "cname.appuioapp.ch"
    steps:
      - run:
          name: DNSimple - make sure all params all available
          command: |
            if [ -z << parameters.token >> ] || [ -z << parameters.account_id >> ] || [ -z << parameters.zone_id >> ] || [ -z << parameters.subdomain >> ]; then
              echo "ERROR: required variables are not specified, check your script invocation"
              exit 1
            fi
      - run:
          name: DNSimple - sending request
          command: |
            shopt -s expand_aliases
            status_code=$(curl --write-out %{http_code} --silent --output /dev/null --request POST "https://api.dnsimple.com/v2/<< parameters.account_id >>/zones/<< parameters.zone_id >>/records" \
            --header "Authorization: Bearer << parameters.token >>" \
            --header 'Content-Type: application/json' \
            --header 'Accept: application/json' \
            --data "{\"name\": \"<< parameters.subdomain >>\",\"type\": \"CNAME\",\"content\": \"<< parameters.content >>\",\"ttl\": \"600\"}")
            case "$status_code" in
              "201")
                echo "New record was successfully added to your domain";
                exit 0;
                ;;
              "400")
                echo "ERROR: A required parameter or the request is invalid";
                exit 1;
                ;;
              "401")
                echo "ERROR: Unauthenticated. Please make sure to add the required keys";
                exit 1;
                ;;
              "500" | "502" | "503" | "504")
                echo "Uh oh, something went wrong on DNSimple’s end";
                exit 1;
                ;;    
            esac
